# Generated by Django 4.1.4 on 2023-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('matric_number', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(choices=[('m', 'male'), ('f', 'female')])),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('next_of_kin_first_name', models.CharField(max_length=20)),
                ('next_of_kin_last_name', models.CharField(max_length=20)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('year_admitted', models.DateField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
