# Generated by Django 4.1.4 on 2023-02-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
