# Generated by Django 4.1.4 on 2023-02-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='payments', max_length=20),
            preserve_default=False,
        ),
    ]
